apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: esmaster1
  name: esmaster1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: esmaster1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: esmaster1
        app: esmaster1
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.appVersion }}"
        imagePullPolicy: Always
        name: esmaster1
        env:
          - name: CLUSTER_NAME
            value: "escluster01"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          - name: HTTP_PORT
            value: "9200"
          - name: NODE_NAME
            value: "${HOSTNAME}"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_DATA
            value: "false"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}