apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-esmaster1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/docker/escluster01/esmaster/config
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
            - 10.200.101.207
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}