apiVersion: v1
kind: Service
metadata:
  name: esclient1
spec:
  selector:
    app: esclient1
  ports:
  - name: esclient1
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}