apiVersion: v1
kind: Service
metadata:
  name: esmaster1
spec:
  selector:
    app: esmaster1
  ports:
  - name: esmaster1
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}