apiVersion: v1
kind: Service
metadata:
  name: esdata1
spec:
  selector:
    app: esdata1
  ports:
  - name: esdata1
    port: 9200
    protocol: TCP
    targetPort: 9200
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}