apiVersion: v1
kind: Service
metadata:
  name: esmaster1
spec:
  selector:
    app: esmaster1
#  ports:
#  - name: esmaster1
#    nodePort: {{ .Values.service.nodePortNumber }}
#    port: {{ .Values.service.port }}
#    protocol: TCP
#    targetPort: {{ .Values.service.port }}
#  sessionAffinity: None
#  type: {{ .Values.service.type }}
status:
  loadBalancer: {}