apiVersion: v1
kind: Service
metadata:
  name: esmaster1
  namespace: elasticsearch
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
