apiVersion: v1
kind: Service
metadata:
  name: esclient1
  namespace: elasticsearch
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-elasticsearch-esclient1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
