apiVersion: v1
kind: Service
metadata:
  name: esmaster1
spec:
  selector:
    app: esmaster1
  ports:
  - name: esmaster1
    nodePort: 30092
    port: 9200
    protocol: TCP
    targetPort: 9200
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}